// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7AUPL_0alRAWCYtP4fqx3dsUVIRDtTo',
    appId: '1:381948043789:web:c37a830b0254b51336eb44',
    messagingSenderId: '381948043789',
    projectId: 'complex-88805',
    authDomain: 'complex-88805.firebaseapp.com',
    storageBucket: 'complex-88805.appspot.com',
    measurementId: 'G-5ZCKJ4WM43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC93Xrufin7AD1nwDK9ftpGSqBTPczx3bk',
    appId: '1:381948043789:android:cab96d134b1bdc5b36eb44',
    messagingSenderId: '381948043789',
    projectId: 'complex-88805',
    storageBucket: 'complex-88805.firebasestorage.app',
  );

}